version: "3"
services:
  reikai-kouza:
    build:
      context: .
      dockerfile: ./docker/reikai-kouza/Dockerfile
    container_name: reikai-kouza
    ports:
      - 10080:10080
    volumes:
      - .:/home/KMC/reikai-kouza
      - reikai-kouza__node_modules:/home/KMC/reikai-kouza/node_modules
    links:
      - reikai-kouza-db
  reikai-kouza-slack-api-test-server:
    build:
      context: .
      dockerfile: ./docker/slack-api-test-server/Dockerfile
    container_name: reikai-kouza--slack-api-test-server
    ports:
      - "5500:80"
    volumes:
      - .:/home/KMC/slack-api-test-server
      - reikai-kouza--slack-api-test-server__node_modules:/home/KMC/slack-api-test-server/node_modules
    links:
      - reikai-kouza-db
  reikai-kouza-db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: reikai-kouza--db
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd!
volumes:
  reikai-kouza__node_modules:
  reikai-kouza--slack-api-test-server__node_modules:
